// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkLRxp0zlL7fabBzMij2UQEcE0xE8wdQ',
    appId: '1:257083139640:web:48c25236db7d73f3dfa8cd',
    messagingSenderId: '257083139640',
    projectId: 'student-manager-8eb38',
    authDomain: 'student-manager-8eb38.firebaseapp.com',
    storageBucket: 'student-manager-8eb38.firebasestorage.app',
    measurementId: 'G-7VX9ED9DT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWeqb1bEOS8xtCdW2Rbe80_RB05Z4qs9k',
    appId: '1:257083139640:android:dbcea8f56875a7cedfa8cd',
    messagingSenderId: '257083139640',
    projectId: 'student-manager-8eb38',
    storageBucket: 'student-manager-8eb38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIQ2GwxQJHA0WhzzjyN8BZTaBlYupEr4M',
    appId: '1:257083139640:ios:26728fa7c35952fcdfa8cd',
    messagingSenderId: '257083139640',
    projectId: 'student-manager-8eb38',
    storageBucket: 'student-manager-8eb38.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIQ2GwxQJHA0WhzzjyN8BZTaBlYupEr4M',
    appId: '1:257083139640:ios:26728fa7c35952fcdfa8cd',
    messagingSenderId: '257083139640',
    projectId: 'student-manager-8eb38',
    storageBucket: 'student-manager-8eb38.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNkLRxp0zlL7fabBzMij2UQEcE0xE8wdQ',
    appId: '1:257083139640:web:3e7bf263de82e2b3dfa8cd',
    messagingSenderId: '257083139640',
    projectId: 'student-manager-8eb38',
    authDomain: 'student-manager-8eb38.firebaseapp.com',
    storageBucket: 'student-manager-8eb38.firebasestorage.app',
    measurementId: 'G-Q2WTLZZYJW',
  );
}
